[package]
name = "lcov2xml"
version = "1.0.11"
edition = "2024"
rust-version = "1.87"
description = "convert LCOV info file to cobertura XML format"
repository = "https://github.com/mike-kfed/lcov2cobertura"
license = "Apache-2.0"
keywords = ["cobertura", "coverage", "gitlab", "lcov"]
categories = ["command-line-utilities"]

[workspace]

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6", default-features = false, features = ["derive", "help", "std", "usage"] }
lcov = "0.8.2"
lcov2cobertura = { path = "lcov2cobertura", version = "1.0.6" }

[dev-dependencies]
quick-xml = "0.42.0"

[lints.clippy]
complexity = "deny"
pedantic = "deny"
perf = "deny"
style = "deny"
suspicious = "deny"

[lints.rust]
ambiguous_associated_items = "forbid"
coherence_leak_check = "forbid"
conflicting_repr_hints = "forbid"
const_evaluatable_unchecked = "forbid"
deref_into_dyn_supertrait = "forbid"
forbidden_lint_groups = "allow"
ill_formed_attribute_input = "forbid"
invalid_doc_attributes = "forbid"
invalid_type_param_default = "forbid"
late_bound_lifetime_arguments = "forbid"
legacy_derive_helpers = "forbid"
macro_expanded_macro_exports_accessed_by_absolute_paths = "forbid"
missing_docs = "deny"
nonstandard_style = { level = "deny", priority = -1 }
patterns_in_fns_without_body = "forbid"
private_bounds = "forbid"
private_interfaces = "forbid"
proc_macro_derive_resolution_fallback = "forbid"
pub_use_of_private_extern_crate = "forbid"
rust_2018_idioms = { level = "deny", priority = -1 }
rust_2021_compatibility = { level = "deny", priority = -1 }
semicolon_in_expressions_from_macros = "forbid"
uninhabited_static = "forbid"
unsafe_code = "forbid"
unstable_name_collisions = "forbid"
warnings = "deny"

[profile.release]
opt-level = "s"
strip = "symbols"
lto = "fat"
