[package]
name = "lcov2cobertura"
version = "1.0.11"
edition = "2024"
rust-version = "1.87"
description = "convert LCOV info file to cobertura XML format"
repository = "https://github.com/mike-kfed/lcov2cobertura"
license = "Apache-2.0"
keywords = ["cobertura", "coverage", "gitlab", "lcov"]

[lib]
name = "lcov2cobertura"

[dependencies]
anyhow = "1.0.102"
quick-xml = "0.41.0"
regex = "1.12.3"
rustc-demangle = "0.1.27"

[lints.clippy]
complexity = "forbid"
expect_used = "deny"
panic = "deny"
pedantic = "deny"
perf = "forbid"
style = "forbid"
suspicious = "forbid"
unimplemented = "deny"
unwrap_in_result = "deny"
unwrap_used = "deny"

[lints.rust]
ambiguous_associated_items = "forbid"
coherence_leak_check = "forbid"
conflicting_repr_hints = "forbid"
const_evaluatable_unchecked = "forbid"
deref_into_dyn_supertrait = "forbid"
forbidden_lint_groups = "allow"
ill_formed_attribute_input = "forbid"
invalid_doc_attributes = "forbid"
invalid_type_param_default = "forbid"
late_bound_lifetime_arguments = "forbid"
legacy_derive_helpers = "forbid"
macro_expanded_macro_exports_accessed_by_absolute_paths = "forbid"
missing_docs = "deny"
nonstandard_style = { level = "deny", priority = -1 }
patterns_in_fns_without_body = "forbid"
private_bounds = "forbid"
private_interfaces = "forbid"
proc_macro_derive_resolution_fallback = "forbid"
pub_use_of_private_extern_crate = "forbid"
rust_2018_idioms = { level = "deny", priority = -1 }
rust_2021_compatibility = { level = "deny", priority = -1 }
semicolon_in_expressions_from_macros = "forbid"
uninhabited_static = "forbid"
unsafe_code = "forbid"
unstable_name_collisions = "forbid"
warnings = "deny"
