[package]
name = "lcov2cobertura"
version = "1.0.7"
edition = "2021"
license = "Apache-2.0"
description = "convert LCOV info file to cobertura XML format"
repository = "https://github.com/mike-kfed/lcov2cobertura"
keywords = ["coverage", "gitlab", "cobertura", "lcov"]
rust-version = "1.81"

[dependencies]
anyhow = "1.0.100"
quick-xml = "0.38.4"
regex = "1.12.2"
rustc-demangle = "0.1.26"

[lib]
name = "lcov2cobertura"

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"
missing_docs = "deny"

[lints.clippy]
unwrap_used = "deny"
panic = "deny"
expect_used = "deny"
unimplemented = "deny"
all = "deny"
pedantic = "deny"
